"""Initial schema

Revision ID: b3c9469126f0
Revises: 
Create Date: 2026-04-09 14:27:35.975198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c9469126f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('term_search_done', sa.Boolean(), nullable=False),
    sa.Column('abbr_search_done', sa.Boolean(), nullable=False),
    sa.Column('term_defs_done', sa.Boolean(), nullable=False),
    sa.Column('abbr_defs_done', sa.Boolean(), nullable=False),
    sa.Column('term_conflicts_done', sa.Boolean(), nullable=False),
    sa.Column('abbr_conflicts_done', sa.Boolean(), nullable=False),
    sa.Column('finding_abbr_chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finding_term_chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('defining_abbrs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('defining_terms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_abbr_conflicts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_term_conflicts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('term_batches_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('term_batches_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('abbr_batches_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('abbr_batches_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed_term', 'completed_abbr', 'completed', 'error')", name='ck_document_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=True)
    op.create_table('global_dictionary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=4), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_dictionary_word'), 'global_dictionary', ['word'], unique=True)
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transliteration_entries',
    sa.Column('abbr', sa.String(length=20), nullable=False),
    sa.Column('ru_variant', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transliteration_entries_id'), 'transliteration_entries', ['id'], unique=True)
    op.create_table('chunks',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_doc_id'), 'chunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=True)
    op.create_table('extracted_items',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_items_chunk_id'), 'extracted_items', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_id'), 'extracted_items', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_items_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_chunk_id'), table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_doc_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_transliteration_entries_id'), table_name='transliteration_entries')
    op.drop_table('transliteration_entries')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_global_dictionary_word'), table_name='global_dictionary')
    op.drop_table('global_dictionary')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
